apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stashapp
  name: stashapp
  namespace: temp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stashapp
  template:
    metadata:
      labels:
        app: stashapp
    spec:
      containers:
      - name: shell
        image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
        command: ["/bin/sh"]
        args: ["-c", "sleep 3600"]
        # volumeMounts:
        # - mountPath: /config
        #   name: target-pvc
      # volumes:
      # - name: target-pvc
      #   persistentVolumeClaim:
      #     claimName: stashapp-pvc
      #     readOnly: false
        