apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stashapp
  name: stashapp
  namespace: temp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stashapp
  template:
    metadata:
      labels:
        app: stashapp
    spec:
      containers:
      - name: shell
        image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
        command: ["/bin/sh"]
        args: ["-c", "sleep 3600"]
        # volumeMounts:
        # - mountPath: /config
        #   name: target-pvc
      # volumes:
      # - name: target-pvc
      #   persistentVolumeClaim:
      #     claimName: stashapp-pvc
      #     readOnly: false
        