apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ocr
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/component: ocr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: ocr
    spec:
      containers:
        - name: gotenberg
          env:
            - name: CHROMIUM-DISABLE-JAVASCRIPT
              value: "true"
            - name: CHROMIUM_ALLOW_LIST
              value: "file:///tmp/.*"
          image: gotenberg/gotenberg:8@sha256:36c925776fa0db0fd1030408d131fde7ac3453027a559883555155b72adb16a7
          ports:
            - name: gotenberg-http
              containerPort: 3000
              protocol: TCP
        - name: tika
          image: apache/tika:3.3.0.0-full@sha256:ecdd37e204308266b1f8e28569f8516ebd5b96d7a4518a71d3904710b20c03b3
          ports:
            - name: tika-http
              containerPort: 9998
              protocol: TCP
      restartPolicy: Always