apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
  name: prowlarr
  namespace: prowlarr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
        - name: restore-from-backup
          image: alpine@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
          command: ["sh", "-c"]
          args:
            - |
              if [ "$RESTORE_BACKUP" = "1" ]; then
                echo "Restoring backup from original PVC..."
                apk add --no-cache rsync
                rsync -avh --delete /backup/ /data/
              else
                echo "Skipping backup restore"
              fi
          env:
            - name: RESTORE_BACKUP
              value: "0" # Set this to "0" to skip restore
          volumeMounts:
            - name: prowlarr-config
              mountPath: /data
            # - name: prowlarr-backup-storage
            #   mountPath: /backup
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest@sha256:3950b5e48cf4ba9dab78fe14038dd7f062e66b7b4ab368b02c94a13f6a3dae9f
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/Los_Angeles"
          ports:
          - name: http
            containerPort: 9696
          volumeMounts:
          - name: prowlarr-config
            mountPath: /config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-pvc
            readOnly: false
        # - name: prowlarr-backup-storage ## Uncomment this and set claimname to PVC
        #   persistentVolumeClaim:
        #     claimName: pvc-38431b7e-e28b-495b-9420-ec7261edd2a2
        #     readOnly: false

