include:
  - openbao.hcl.yml

services:
  openbao:
    image: ghcr.io/openbao/openbao:2.6.2
    container_name: openbao-prod-d1
    hostname: openbao-prod-d1
    restart: unless-stopped

    command:
      - server
      
    # ports:
    #   - "8200:8200"

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.openbao-transit.rule=HostSNI(`openbao.openbao-transit-prod-d1.mclacken.net`)"
      - "traefik.tcp.routers.openbao-transit.entrypoints=websecure"
      - "traefik.tcp.routers.openbao-transit.tls=true"
      - "traefik.tcp.routers.openbao-transit.tls.passthrough=true"

      - "traefik.tcp.services.openbao-transit.loadbalancer.server.port=8200"

    configs:
      - source: openbao.hcl
        target: /openbao/config/openbao.hcl
        mode: "0444"

    volumes:
      - openbao-data:/openbao/file

      - /etc/openbao/tls/ca.crt:/openbao/tls/ca.crt:ro
      - /etc/openbao/tls/server.crt:/openbao/tls/server.crt:ro
      - /etc/openbao/tls/server.key:/openbao/tls/server.key:ro

volumes:
  openbao-data:

networks:
  proxy:
    name: proxy
    external: true