include:
  - openbao.hcl.yml

services:
  openbao:
    image: ghcr.io/openbao/openbao:2.6.2
    container_name: openbao-prod-d1
    hostname: openbao-prod-d1
    restart: unless-stopped

    command:
      - server
      
    ports:
      - "8200:8200"

    configs:
      - source: openbao.hcl
        target: /openbao/config/openbao.hcl
        mode: "0444"

    volumes:
      - openbao-data:/openbao/file

      - /etc/openbao/bootstrap/bootstrap-ca.crt:/openbao/tls/bootstrap-ca.crt:ro
      - /etc/openbao/bootstrap/transit-server.crt:/openbao/tls/server.crt:ro
      - /etc/openbao/bootstrap/transit-server.key:/openbao/tls/server.key:ro

volumes:
  openbao-data: