name: openbao-prod-d1
services:
  openbao:
    image: ghcr.io/openbao/openbao:2.6.2
    container_name: openbao-prod-d1

    hostname: openbao-prod-d1

    restart: unless-stopped

    command:
      - server
      - -config=/openbao/config/openbao.hcl

    ports:
      - "8200:8200"

    volumes:
      - openbao-data:/openbao/data

      - ./openbao.hcl:/openbao/config/openbao.hcl:ro

      - /etc/openbao/bootstrap/bootstrap-ca.crt:/openbao/tls/bootstrap-ca.crt:ro
      - /etc/openbao/bootstrap/transit-server.crt:/openbao/tls/server.crt:ro
      - /etc/openbao/bootstrap/transit-server.key:/openbao/tls/server.key:ro

volumes:
  openbao-data: