apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-eso-jwk-rs256-private-key-external-secret
  namespace: authelia-prod-d1
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/component: program-secret
    app.kubernetes.io/instance: authelia-prod-d1
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-vault-store
  target:
    name: authelia-jwk-rs256-private-key-secret
  data:
    - secretKey: key
      remoteRef:
        key: authelia/prod-d1/jwk-rs256-private-key
        property: key


# openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out jwk-rs256-private-key.pem

# openssl rsa -in jwk-rs256-private-key.pem -pubout -out jwk-rs256-public-key.pem

# bao kv put -mount=kube-prod-d1 authelia/prod-d1/jwk-rs256-private-key \
#   key=@jwk-rs256-private-key.pem \
#   pub-key=@jwk-rs256-public-key.pem