apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaresolverr
  name: flaresolverr
  namespace: flaresolverr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
          env:
          - name: LOG_LEVEL
            value: "info"
          ports:
          - name: proxy
            containerPort: 8191

