services:
  composeflux:
    image: ghcr.io/veerendra2/composeflux:latest@sha256:ea938535303a67ef8284bf7039df4c00f1fdee164b407d750eeac0d620c35f74
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.ssh/composeflux_id_rsa:/.ssh/composeflux_id_rsa:ro
      - compose-stack:/opt/compose-stack

volumes:
  compose-stack: