services:
  composeflux:
    image: ghcr.io/veerendra2/composeflux:latest@sha256:78ba0df5ad31ebb5e2148e59fb432004ff691739cd9b6187c2d5ddfb223391ba
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.ssh/composeflux_id_rsa:/.ssh/composeflux_id_rsa:ro
      - compose-stack:/opt/compose-stack

volumes:
  compose-stack: