services:
  composeflux:
    image: ghcr.io/veerendra2/composeflux:latest@sha256:2941a97b863c46698ef735e39744b969b5152155c6a77a83133158068e4a4286
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.ssh/composeflux_id_rsa:/.ssh/composeflux_id_rsa:ro
      - /opt/compose-stack:/opt/compose-stack

volumes:
  compose-stack: