apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-manage
  namespace: argocd
spec:
  project: default
  sources:
    - chart: argo-cd
      RepoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.7.17
      helm:
        valueFiles:
          - $values/kubernetes/argocd/argocd-prod-d1/values.yaml
    - repoURL: https://github.com/dj346/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
