global:
  image:
    tag: v2.8.3 # Specific ArgoCD version
server:
  service:
    type: LoadBalancer # Use LoadBalancer for external access
  extraArgs:
    - --insecure
dex:
  enabled: false # Disable Dex if not using OIDC