apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-authelia-trusted-ca-chains-external-secret
  namespace: eso
spec:
  refreshInterval: 1h
  target:
    name: eso-authelia-trusted-ca-chains-secret
    template:
      type: Opaque
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "^(?!(?:default|kube-node-lease|kube-public)$).*"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "authelia-prod-d1"
      data:
        ca1.crt: "{{ .ca_chain_1 }}"
        ca2.crt: "{{ .ca_chain_2 }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: eso-ca-chain-cnpg-prod-d1-ica2-vault-dynamic-secret
      rewrite:
        - regexp:
            source: "^ca_chain$"
            target: "ca_chain_1"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: eso-ca-chain-redis-prod-d1-ica2-vault-dynamic-secret
      rewrite:
        - regexp:
            source: "^ca_chain$"
            target: "ca_chain_2"