apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: eso-ca-chain-redis-prod-d1-ica2-vault-dynamic-secret
  namespace: eso
spec:
  provider:
    server: "https://openbao-application-internal.openbao:8200"
    caProvider:
      type: Secret
      namespace: eso
      name: openbao-server-ca
      key: ca.crt
    tls:
      certSecretRef:
        name: eso-vault-client-certificate-secret
        namespace: eso
        key: tls.crt
      keySecretRef:
        name: eso-vault-client-certificate-secret
        namespace: eso
        key: tls.key
    auth:
      kubernetes:
        mountPath: "kubernetes/kube-prod-d1"
        role: "eso-kube-prod-d1"
        serviceAccountRef:
          name: "eso-issuer-service-account"
          namespace: "eso"
          audiences:
            - "eso-vault-auth"
  method: "GET"
  path: "pki/kube-prod-d1/redis-prod-d1/ICA2/cert/ca_chain"
  resultType: "Data"
