include:
  - traefik.config.yml

services:
  traefik:
    image: traefik:v3.7.13@sha256:f86a2cab1b5c649070c49f883c743dd32d8485a56e3368c5f93b9e91f1e91259
    container_name: traefik-prod-d1
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    ports:
      - "80:80"
      - "443:443"

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard.rule=Host(`traefik.openbao-transit-prod-d1.mclacken.net`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

    networks:
      - proxy

    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    name: proxy
    external: true