services:
  traefik:
    image: traefik:v3@sha256:5203c3f39ca70de6790d964624e042463ffbd57715bc82be155cf224c0dd5144
    container_name: traefik-prod-d1
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    ports:
      - "80:80"
      - "443:443"

    networks:
      - proxy

    configs:
      - source: traefik.yml
        target: /etc/traefik/traefik.yml

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    name: proxy