apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-sample
  namespace: default
spec:
  image: chrislusf/seaweedfs:latest@sha256:f5515a88db87397b65b613d604d88dc9855dcca9de6d0ed5a95bf8cf5572f03c
  volumeServerDiskCount: 1
  hostSuffix: seaweed.abcdefg.com
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
  volume:
    replicas: 1
    requests:
      storage: 2Gi
  filer:
    replicas: 2
    # s3: true          # Enable S3 API
    iam: true         # Enable embedded IAM
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
  # Optional: Standalone IAM service
  # iam:
  #   replicas: 1
  #   port: 8111